version: '3'
services:
  jenkins:
    container_name: jenkins
    build: .
    ports:
      - '8088:8080'
      - '50000:50000'
    volumes:
      - 'jenkins_data:/jenkins_config'
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
volumes:
  jenkins_data:
    driver: local
  jenkins_home:
    driver: local
